sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a4d2c0b15b94444b173e
    on_success: always
    on_failure: always
    on_start: never
